### ISSUE TITLE
Console Throws Dependency Error with v1.0.0-beta3.

### ISSUE THREAD

**Issue by ReservedDeveloper** [hautelook/AliceBundle#107]
Attempting to use the new ODM support. I've loaded in the latest beta release, and the [ODM library](https://github.com/doctrine/mongodb-odm) and [ODM Bundle](https://github.com/doctrine/DoctrineMongoDBBundle), I'm getting the following error on the console:

```sh 
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                                    
  The service "hautelook_alice.doctrine.generator.loader_generator" has a dependency on a non-existent service "hautelook_alice.doctrine.orm.fixtures_finder".
```

I've got the ODM & Alice bundles enabled in the AppKernel, and the following config block:
```yml
hautelook_alice:
    locale: en_US       # Locale to used for faker; must be a valid Faker locale otherwise will fallback to en_EN
    seed: 1             # A seed to make sure faker generates data consistently across runs, set to null to disable
    persist_once: false # Only persist objects once if multiple files are passed
    db_drivers:
        orm: false #attempting to manually disable ORM to prevent error
        mongodb: true
doctrine_mongodb:
    connections:
        default:
            server: "%mongo_database_host%"
            options: {}
    document_managers:
        default:
            auto_mapping: true
```

Any insight would be appreciated!
