### ISSUE TITLE
Strange LoadingLimitException case

### ISSUE THREAD

**Issue by Soullivaneuh** [hautelook/AliceBundle#117]
With the following fixtures files:

```yml
AppBundle\Entity\Server:
    server (template):
        hostedDomain: sample.net
        mac: <macAddress()>
        sshUser: toor
        sshPort: 4242
        mysqlHost: localhost
        mysqlRoot: <password()>
        webServer: apache
        webServerSslListen: 0.0.0.0
        webServerSslPort: 443
        mysqlServer: true
        status: 1
        installedAt: <dateTime()>
    server_{1..9} (extends server):
        name: server_<current()>
```

I got the following error:

```bash
 [Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException]                                                                                         
  Loading files limit of 5 reached. Could not load the following files: /home/sullivan/projects/project/src/AppBundle/DataFixtures/ORM/server.yml
```

And it works well if I remove this line:

```yml
        installedAt: <dateTime()>
```

I don't think this is the real error. I think upper exception is catched but no way to know what is happening.

Any solution for this?

**Comment by theofidry** [comment]
If you have the time to debug it should be around [here](https://github.com/hautelook/AliceBundle/blob/master/src/Alice/DataFixtures/Loader.php#L79). Maybe the exception should give a part of the `\UnexceptedException` message or have a logger to log it rather than silencing it

**Comment by Soullivaneuh** [comment]
It would be great to list all encountered exceptions when limit is reached on cli.

**Comment by Soullivaneuh** [comment]
Or just show the exception message while processing. With the verbose option maybe?

**Comment by theofidry** [comment]
Well, the thing is it's not something happening in the command but inside the loader, which have no idea about the verbosity set. So we can either put the messages of the exceptions encountered when the `LoadingLimitException` is thrown or put that in a logger.

**Comment by Soullivaneuh** [comment]
I any case, having thoses message on cli result would be nicer. :-)

**Comment by Soullivaneuh** [comment]
Just having an idea: Why not store each error messages and display all when the limit is reached?

Could be done with a verbose option (`-v`) for people that not want a huge display?

What do you think? Could work on it to see if it's possible.

**Comment by theofidry** [comment]
It would be great to have a verbose mode, but as I said the issue is that the loader has no idea of the verbosity. It might be worth logging it but as always logging can easily lead to performance issues.

If you have some ideas about it I'm all ears. But the first (easy) move would be to enhance the `LoadingLimitException` message.

**Comment by Soullivaneuh** [comment]
> But the first (easy) move would be to enhance the `LoadingLimitException` message.

I would start this way so.

**Comment by supertanuki** [comment]
I encountered this bug in a different case, when a fixture made a reference to one in other file.

I use AliceBundleExtension https://github.com/theofidry/AliceBundleExtension and I load 2 files:
```
    And the fixtures file "Event.yml" is loaded
    And the fixtures file "Participant.Type.yml" is loaded
```

In Participant.Type.yml there is a reference to Event.yml : 
```
Participant\Type:
    visitor:
        event: @event_1
        title: Visitor
```

The Event.yml is loaded but not the Participant.Type.yml. I have the following error:
Loading files limit of 5 reached. Could not load the following files: (...)/Participant.Type.yml (Hautelook\AliceBundle\Alice\DataFixtures\LoadingLimitException)

If I remove this reference `event: @event_1`, Participant.Type.yml  is loaded successfully.
