### ISSUE TITLE
Custom Provider : Circular Reference

### ISSUE THREAD

**Issue by adm-husker** [hautelook/AliceBundle#129]
Hello, i'm trying to create a custom faker provider but i'm stuck with a circular reference exception. 

Here is my configuration :

```json
// composer.json
// ...
    "doctrine/doctrine-fixtures-bundle": "^2.2",
    "hautelook/alice-bundle": "v1.0.0-beta.5"
// ...
```

```yaml
# config_dev.yml
hautelook_alice:
    db_drivers:
        orm: ~
    locale: fr_FR
    seed: 1
    persist_once: true
    loading_limit: 5
```

```yaml
# AppBundle/Resources/config/services.yml
services:
  faker.provider.markdownpost:
      class: AppBundle\DataFixtures\Faker\Provider\MarkdownPostProvider
      arguments: [ @hautelook_alice.faker ]
      tags: [ { name: hautelook_alice.faker.provider } ]
```

```php
<?php

// src/AppBundle/DataFixtures/Faker/Provider/MarkdownPostProvider.php

namespace AppBundle\DataFixtures\Faker\Provider;

class MarkdownPostProvider extends \Faker\Provider\Base
{
    const MAX_PARAGRAPHS = 10;

    public function markdownPost()
    {
        $paragraphs = $this->generator->paragraphs(self::MAX_PARAGRAPHS);

        // TODO : implements random markdown generation

        return $paragraphs;
    }
}
```
  
```bash
  [Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]  
  Circular reference detected for service "faker.provider.markdownpost", path          
  : "hautelook_alice.doctrine.command.deprecated_load_command -> hautelook_al          
  ice.fixtures.loader -> hautelook_alice.alice.fixtures.loader -> hautelook_a          
  lice.faker.provider_chain -> faker.provider.markdownpost -> hautelook_alice          
  .faker".                                                                             
```

Did I misunderstand something?

**Comment by theofidry** [comment]
Erf no it's my fault didn't thought of that. The problem is pretty simple: the faker service `hautelook_alice.faker` ask for ALL providers, including the one you're declaring... which requires `hautelook_alice.faker`.

I'll try to find a solution for this case. In the meantime you can easily solve your problem by not extending `\Faker\Provider\Base`. Most Faker's providers methods are static so you rarely need to extend one and have to inject a generator.

**Comment by theofidry** [comment]
Well, there is not much way to get around that if not introducing an "empty" Faker service to be used for providers.

@Soullivaneuh maybe you have something to say about this?

**Comment by Soullivaneuh** [comment]
Well, I didn't write any custom provider for now but I'll do it soon.

First question: Why extending `\Faker\Provider\Base` is needed?

**Comment by theofidry** [comment]
Most of the time (I think I had to extend a Faker provider only once) this is not required but I guess sometimes it makes sense to do that...

**Comment by Soullivaneuh** [comment]
Hmm... maybe create a faker factory or something else?

**Comment by theofidry** [comment]
Actually Faker already use a factory... I've just created an instance using this factory and to which I pass all the providers. That's all there is to it. But indeed, if you want to inject a faker instance for a provider, as every provider extending the base provider do, it will create a circular reference.

I guess the question will be more: do let the user creating his own faker instance dedicated for providers or do we create one? Either will require some change in the doc, but the later pose the problem of the name.

**Comment by Soullivaneuh** [comment]
Well, I think I got the problem to with [CronExpressionGenerator](https://github.com/swekaj/CronExpressionGenerator) plugin.

Service:

```yaml
faker.provider.cron: # https://packagist.org/packages/swekaj/cron-expression-generator
    class: CronExpressionGenerator\FakerProvider
    arguments: [ @hautelook_alice.faker ]
    tags:
        - { name: hautelook_alice.faker.provider }
```

Error:

```
  [Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]                                                                                                                                                                                            
  Circular reference detected for service "faker.provider.cron", path: "hautelook_alice.doctrine.command.deprecated_load_command -> hautelook_alice.fixtures.loader -> hautelook_alice.alice.fixtures.loader -> hautelook_alice.faker.provider_chain -> faker.provider.cron ->   
  hautelook_alice.faker".                                                                                                                                                                                                                                                        
```

But the Base extension is correct because the maintainer use internal methods of the Faker: https://github.com/swekaj/CronExpressionGenerator/blob/65cdbfa889cb4d00e2878b288ba43554b6ce8011/src/FakerProvider.php

So I think we have to find a solution to handle it.
