### ISSUE TITLE
Performance benchmarking

### ISSUE THREAD

**Issue by theofidry** [hautelook/AliceBundle#139]
It would be nice to have a kind of test with very heavy use of the bundle and profile it in order to find some path for optimisation and making it faster.

cc @Soullivaneuh

**Comment by Soullivaneuh** [comment]
Nice idea, would be helpful for project with huge sets of fixtures.

Any proposition about how to? Tools to recommend?

**Comment by theofidry** [comment]
Well, I was thinking of a simple Symfo apply with just Doctrine and a large set of entities with all kind of relations, bidirectional or not, and lots of fixtures... Then try to see how what's the issues are with a Blackfire profile and debug tools.

My guess is:

* there is some memory leaks from Doctrine, logging and such
* we don't use cache at all
* explore if we can multithread it, provided it doesn't cause too much trouble 

The best thing IMO is to have a dedicated application for that, just created a repo for it: [AliceBundleBenchmarking](https://github.com/theofidry/AliceBundleBenchmarking) (still nothing in it).

To which extend are you currently using AliceBundle @Soullivaneuh?

**Comment by Soullivaneuh** [comment]
> To which extend are you currently using AliceBundle @Soullivaneuh?

I'm sorry I don't understand your question. What do you mean by extend?

> there is some memory leaks from Doctrine, logging and such

Yeah. One improvement could be to regularly flush and clean entities. Actually, more the fixture objects are, longer the process is.

**Comment by theofidry** [comment]
> I'm sorry I don't understand your question. What do you mean by extend?

Do you currently have only a few fixtures files or is it a more heavy use? How does it performs currently? I use AliceBundle v0.2 for a large project but it changed a lot now so I really have no idea of how it will performs right now.

> Yeah. One improvement could be to regularly flush and clean entities. Actually, more the fixture objects are, longer the process is.

Yes I guess, there is some such actions already taken but with no profiling I don't know if it's effective or not.

**Comment by Soullivaneuh** [comment]
I'm using v1.0 beta.

Take this fixtures config:

```yml
AppBundle\Entity\User:
    user (template):
        plainPassword: test
        defaultPassword: false
        enabled: true
        country: @france
        defaultPaymentMethod: @vir
    user_profile (template, extends user):
        email: <email()>
        firstname: <firstName()>
        lastname: <lastName()>
        street1: <streetAddress()>
        city: <city()>
        postalCode: <postcode()>
        phonenumber: <phoneNumber()>
    user_customer_{1..200} (extends user_profile):
        username: user_customer_<current()>
```

And change user number from `200` to `5000` for example.

Launch the fixtures loading command and you will have time for many cups of coffee before ending. :coffee: :coffee: :coffee:  :-)
