### ISSUE TITLE
Get a fixture by reference?

### ISSUE THREAD

**Issue by pstephenson02** [hautelook/AliceBundle#155]
Hi. First of all thank you for your work on this bundle. I tried AliceBundle an old project but I hadn't touched it for a while until today and I am pleased to see how active it's been!

I want to use Alice in tandem with [LiipFunctionalTestBundle](https://github.com/liip/LiipFunctionalTestBundle), which has a convenient method loadFixtureFiles specific for Alice fixtures. The FunctionalTestBundle also has a method to define a *reference* to an object in the Fixture class by calling a setReference method, allowing you to then simply getReference in the test: https://github.com/liip/LiipFunctionalTestBundle#referencing-fixtures-in-tests

I realize this is just a convenience, but is there anything like this in AliceBundle? Or do we need to query the repository to get the fixture objects?

One more question:
My test class loads fixture files in whichever order I define them:

```php
    public function setUp()
    {
        $this->fixtures = $this->loadFixtureFiles(array(
            '@ProposalBundle/DataFixtures/ORM/StandardProposal.yml',
            '@ProposalBundle/DataFixtures/ORM/CAHAnnotation.yml'
        ));
        ...
    }
```

These 2 specific objects above have bi-directional associations to each other. So I would like to have, StandardProposal.yml:

```yml
ICC\ProposalBundle\Entity\StandardProposal:
    standard_proposal_{1..5}:
        name: <name()>
        analysis: <paragraph()>
        bibliography: <paragraph()>
        cost_impact: <paragraph()>
        setCAHAnnotation: @cah_annotation*
```

and then... CAHAnnotation.yml

```yml
ICC\ProposalBundle\Entity\Annotation\CAHAnnotation:
    cah_annotation_{1..5}:
        __construct: [@standard_proposal*]
        errata: <paragraph()>
        display_errata: false
```

However, clearly each of these files depends on the other to load the entire fixture. How would you recommend I deal with this type of situation? Do I essentially need to remove the call to setCAHAnnotation, and query the objects and set that association in the actual test? The project I work on has a pretty crazy data model with lots of objects. I foresee this becoming a bit confusing if I continue and really invest in AliceBundle.

Thanks in advance!
