### ISSUE TITLE
Undefined index when persisting

### ISSUE THREAD

**Issue by xtuc** [hautelook/AliceBundle#167]
Error I get when I try to load the fixtures:
```
[Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined index: 00000000625aab41000000017e09a5d6
````

```yml
hidden\hidden\CoreBundle\Entity\Userhidden:
    superadmin_hidden:
        hiddenFonction: "NA"
        hiddenMatricule: "NA"
        hiddenInsee: "NA"
        hiddenPilotage: 0
        user: @superadmin
```
```yml
hidden\hidden\CoreBundle\Entity\User:
    superadmin:
        username: admin
        email: <email()>
        enabled: 1
        plainPassword: admin
        firstname: hidden
        lastname: hidden
        roles: [ROLE_SUPER_ADMIN]
```

Userhidden entity:
hiddenFonction, hiddenMatricule, hiddenInsee and hiddenPilotage are string/integer columns.
```PHP
....

/**
 * @var \User
 *
 * @ORM\Id
 * @ORM\GeneratedValue(strategy="NONE")
 * @ORM\OneToOne(targetEntity="User")
 * @ORM\JoinColumns({
 *   @ORM\JoinColumn(name="user_id", referencedColumnName="id")
 * })
 */
private $user;
```

UserHidden has a relation to User but the column is also the primary. I guess that's the problem.
