### ISSUE TITLE
Can't run fixtures due to constraints violation, why?

### ISSUE THREAD

**Issue by reypm** [hautelook/AliceBundle#200]
I am trying to write a fixture for the entity shown below but I am getting this error all the time and don't know why or what I am doing wrong.

> [PDOException]
>   SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '58' for key 'msisdn'

This is the fixture:

```
PlatformAdminBundle\Entity\Msisdn:
    msisdn{1..500}:
        msisdn (unique): <phoneNumber()>
        operator: @operator*
        blocked: <boolean(35)>
        createdAt: <dateTimeThisYear()>
        updatedAt: <dateTimeThisYear()>
```

This is the entity definition:

```
/**
 * @ORM\Entity
 * @ORM\Table(name="cm_msisdn", uniqueConstraints={@ORM\UniqueConstraint(name="msisdn", columns={"msisdn"} )})
 */
class Msisdn
{
    use IdentifierAutogeneratedTrait;
    use TimestampableEntity;

    /**
     * @var int
     * @ORM\Column(type="bigint")
     */
    private $msisdn;

    /**
     * @ORM\ManyToOne(targetEntity="Operator")
     */
    private $operator;

    /**
     * @var bool
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $blocked = false;
}
```

And finally this is the config I have for the bundle:

```
hautelook_alice:
    db_drivers:
        orm: ~          # Enable Doctrine ORM if is registered
    locale: es_VE       # Locale to used for faker; must be a valid Faker locale otherwise will fallback to en_EN
    seed: 1             # A seed to make sure faker generates data consistently across runs, set to null to disable
    persist_once: false # Only persist objects once if multiple files are passed
    loading_limit: 5    # Maximum number of time the loader will try to load the files passed
```

What I am missing here?
