### ISSUE TITLE
Update row, same id

### ISSUE THREAD

**Issue by hidabe** [hautelook/AliceBundle#207]
I am trying do:
```yaml
    quad_{1..73}:
        id: <current()>
        quadNumber: <current()>
```

keep same id, and "php app/console hautelook_alice:doctrine:fixtures:load --append", but it no replace file already existing.

How i could do it?
