### ISSUE TITLE
Cross reference

### ISSUE THREAD

**Issue by hidabe** [hautelook/AliceBundle#210]
I am trying do reference between files, i have Quad and QuadRule entities:

Quad 1-M Relation with QuadRule

Next information:
Quad:
```yaml
    quad_1:
        quadNumber: 1
        quadRules: [ @quadrule_1 ]
```
QuadRule:
```yaml
  quadrule_1: { term1: 'D', operand: 'may', term2: '50' }
```

If i write my yaml information in same file, it work, and i have relation in quadrule with quad,
but If i write in diferents files, it not working.

I think that it is a bug,
