### ISSUE TITLE
Blacklist schema/table names

### ISSUE THREAD

**Issue by ju1ius** [hautelook/AliceBundle#211]
Hi,
For a project, I have mappings between two databases (lets's call them "current" & "legacy").
The "legacy" db must be treated as read-only, but I need some mappings to ease progressive migration, which means I must use a single entity manager.
Currently I can't load fixtures into "current" without the command wanting to also purge "legacy", so I'm forced to use the --append flag, and purge "current" manually.

Is it possible to exclude tables to purge either by schema or by table name ?

**Comment by vincentchalamon** [comment]
Hi @ju1ius, thanks for your question. I got a similar problem for the continuous migration of the project in LaFourchette. My opinion is that this problem is specific to the project, so I guess it can't be native in AliceBundle.

To understand precisely your configuration: you have 2 databases (`current` & `legacy`), each of them with a Doctrine connection but only 1 EntityManager? And you want to purge everything except some tables in `current` database?

**Comment by ju1ius** [comment]
> To understand precisely your configuration: you have 2 databases (current & legacy),

Yes.

> each of them with a Doctrine connection but only 1 EntityManager? 

No (I don't think it's possible btw). As the dbs are on the same server, they share the same connection & entity manager. Otherwise (AFAIK) it is not possible to do cross database joins.

Let me explain the setup. I have three bundles:
* CurrentBundle with the entities mapped to the `current` db
* LegacyBundle with the entities from `legacy` db.
* MigrationBundle with some entities that have associations to both CurrentBundle's and LegacyBundle's entities.

CurrentBundle is the new app+persistence model.
All that is in LegacyBundle is read-only.
MigrationBundle will allow users to migrate their content from the `legacy` db to the `current` db.

So in the dev environment I'd like to be able to load fixtures in the `current` db without purging the `legacy` db.

**Comment by ju1ius** [comment]
> My opinion is that this problem is specific to the project,

Although it might be quite rare, cross-db associations are a documented feature of doctrine, so I don't think it is a totally alien use case...

**Comment by vincentchalamon** [comment]
> As the dbs are on the same server, they share the same connection & entity manager.

Not necessary, you can create 1 Doctrine connection & 2 entity managers using custom mappings. For example for our migration, we created 2 bundles like you did: `RestaurantBundle` & `LegacyBundle`. But we provides everything about migration on LegacyBundle, so at the end we should be able to remove this bundle easily and everything about migration :)

I think if you manage correctly your mapping using 2 entity managers, you may be able to prevent resetting your legacy tables using a `if` instance in your override of databases reset.

It should be something like that:
```yml
# config.yml
doctrine:
    dbal:
        connections:
            default:
                ...
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    LaFourchetteRestaurantBundle:  ~
            legacy:
                connection: default
                mappings:
                    LaFourchetteLegacyBundle: ~
```

```php
// features/bootstrap/EntityContext.php
namespace Context;

use Knp\FriendlyContexts\Context\EntityContext as BaseContext;

class EntityContext extends BaseContext
{
    /**
     * @BeforeScenario
     */
    public function beforeScenario($event)
    {
        $this->storeTags($event);

        if ($this->hasTags(['reset-schema', '~not-reset-schema'])) {
            foreach ($this->getEntityManagers() as $name => $entityManager) {
                // This will prevent `legacy` entity manager to be parsed
                if ('legacy' === $name) {
                    continue;
                }
                $connection = $entityManager->getConnection();
                $this->resetSchema($entityManager);
            }
        }
    }
}
```

**Comment by vincentchalamon** [comment]
I hope this other point of view can help you. BTW, if you come to the next Symfony Live in Paris (April 7/8), you can have a complete look about how we manage migration on LaFourchette project. I think it can be very interesting for you :)

**Comment by ju1ius** [comment]
> you can create 1 Doctrine connection & 2 entity managers

Thanks, I'll try it and see if that works ! :+1: 

> if you come to the next Symfony Live in Paris (April 7/8)

Unfortunately, I won't... Will there be a live stream ?

**Comment by vincentchalamon** [comment]
Not sure about the live stream, but I think it will be recorded, so you may be able to see the talk after the live. I'll also share the slides as soon as possible after the live. I'll let you know :)

**Comment by ju1ius** [comment]
Hi,
I tried your solution, but whenever I try to acces an entity that has a cross-db relationship, this exception is thrown:
```
MappingException: The class 'LegacyBundle\Entity\Foo' was not found in the chain configured namespaces
CurrentBundle\Entity, MigrationBundle\Entity
```
This is my doctrine config:
```yaml
doctrine:
    dbal:
        default_connection: current
        connections:
            current:
                ...
    orm:
        default_entity_manager: current
        entity_managers:
            current:
                connection: current
                mappings:
                    CurrentBundle: ~
                    MigrationBundle: ~
            legacy:
                connection: current
                mappings:
                    LegacyBundle: ~
```

**Comment by vincentchalamon** [comment]
So you have some entities relations between MigrationBundle & LegacyBundle, right? It's not possible in Doctrine to have cross-entity-managers relations, this is your main issue I think… Why do you need to separate LegacyBundle & MigrationBundle? They can be merged I think, as they both manage migration. Also, why did you set MigrationBundle in `current` entity manager instead of `legacy` one?

I think, for your migration, you should store your project mapping in CurrentBundle, and everything about migration (legacy mapping, managers, etc…) on your LegacyBundle (so no need MigrationBundle anymore). Like that, you should be able to manage migration in LegacyBundle (which is the main goal of this bundle). Everything at the correct place, or to be clear: _what happens in Vegas stays in Vegas_ :wink:

**Comment by vincentchalamon** [comment]
You should then be able to load data in your LegacyBundle like that:

```php
// src/LegacyBundle/Loader/CustomerLoader.php
namespace LegacyBundle/Loader;

use CurrentBundle\Entity\Customer;
use Doctrine\Bundle\DoctrineBundle\Registry;
use Doctrine\ORM\EntityManagerInterface;
use LegacyBundle\Entity\Customer as LegacyCustomer;

class CustomerLoader implements LoaderInterface
{
    /**
     * @var EntityManagerInterface
     */
    private $currentEntityManager;

    /**
     * @var EntityManagerInterface
     */
    private $legacyEntityManager;

    /**
     * @param Registry $doctrine
     */
    public function __construct(Registry $doctrine)
    {
        $this->currentEntityManager = $doctrine->getManager('current');
        $this->legacyEntityManager = $doctrine->getManager('legacy');
    }

    /**
     * {@inheritdoc}
     */
    public function loadCustomer($legacyCustomerId)
    {
        // This is just to show you how you can manage multiple entity managers
        // in your class. But $legacyCustomer can be directly injected in this method,
        // and retrieved easily from external
        $legacyCustomer = $this->legacyEntityManager->getRepository('LegacyBundle:Customer')
            ->find($legacyCustomerId);
        if (null === $legacyCustomer) {
            // Legacy customer cannot be found
            return;
        }

        $customer = new Customer();
        $customer->setFirstName($legacyCustomer->getFirstName());
        // …

        // Here you save the new migrated customer in your current mapping
        $this->currentEntityManager->persist($customer);
        $this->currentEntityManager->flush($customer);
    }
}
```

**Comment by ju1ius** [comment]
> It's not possible in Doctrine to have cross-entity-managers relations, this is your main issue I think…

Yeah that's why I used one connection & one EM to begin with. Was not 100% sure however.

> Why do you need to separate LegacyBundle & MigrationBundle? They can be merged I think, as they both manage migration. Also, why did you set MigrationBundle in current entity manager instead of legacy one?

The legacy app is a really old one (2004), with a _lot_ of content. The db design is so awful (no PKs, no FKs, no constraints, just to name a few...) that I couldn't even get it to work with the orm other than read-only. Doctrine even fails at updating the schema... So I can't add tables to the legacy db through the orm.

The LegacyBundle in fact is just a read-only interface to the legacy content.

The MigrationBundle will contain the actual migration logic & ui. The model is nothing complicated, just a bunch of entities to link relate legacy entities to the new ones and keep track of the migration state. The ui part is more tricky.

**Comment by ju1ius** [comment]
Maybe there could be a `--filter` option in the `h:d:f:l` command that would do something like this before purging ?
```php
$filter = $input->getOption('filter');
$connection->getConfiguration()->setFilterSchemaAssetsExpression($filter);
```

**Comment by ju1ius** [comment]
Okay, I found a workaround by using a command listener:

```yaml
legacy.listener.command.filter_tables:
    class: LegacyBundle\Command\Listener\FilterTables
    arguments:
        - '@doctrine.dbal.connection'
        - '/^hautelook_alice:.*$/'
        - '/^(?!legacy\.).*$/'
    tags:
        - { name: kernel.event_listener, event: console.command }
```
```php
namespace LegacyBundle\Command\Listener;

use Doctrine\DBAL\Connection;
use Symfony\Component\Console\Event\ConsoleCommandEvent;

class FilterTables
{
    /**
     * @var Connection
     */
    private $connection;
    /**
     * @var string
     */
    private $commandFilter;
    /**
     * @var string
     */
    private $tableFilter;

    /**
     * FilterTablesCommandListener constructor.
     *
     * @param Connection $connection
     * @param string     $commandFilter
     * @param string     $tableFilter
     */
    public function __construct(Connection $connection, $commandFilter, $tableFilter)
    {
        $this->connection = $connection;
        $this->commandFilter = $commandFilter;
        $this->tableFilter = $tableFilter;
    }

    public function onConsoleCommand(ConsoleCommandEvent $event)
    {
        $command = $event->getCommand();

        if (preg_match($this->commandFilter, $command->getName())) {
            $this->connection->getConfiguration()->setFilterSchemaAssetsExpression($this->tableFilter);
        }
    }
}
```

Thanks for your input ! :wink:

**Comment by ju1ius** [comment]
Turns out the above is in fact not needed !  :sweat_smile:
I just needed to configure doctrine this way:
```yaml
doctrine:
  dbal:
    connections:
      current:
        schema_filter: '/^(?!legacy\.).*$/'
```
Maybe that would be nice to document here, since the info is not that easy to find.
It is in the symfony doctrine config [reference](http://symfony.com/doc/current/reference/configuration/doctrine.html), but it was not clear to me that you could still map entities to the ignored tables !
