### ISSUE TITLE
How to add ManyToMany in yaml file ?

### ISSUE THREAD

**Issue by RomainMarecat** [hautelook/AliceBundle#223]
didn't see how to add ArrayCollection of entities into the documentation ?
```yaml
AppBundle\Entity\User:
    user{1..100}:
        username (unique): <username()>
        email (unique): <email()>
        # vouchers: ['@voucher<numberBetween(1, 100)>']

Zeemono\VoucherBundle\Entity\Voucher:
    voucher{1..200}:
        name: <text(255)>
        slug (unique): <sha256()>
        code (unique): <sha256()>
        cashAvailable: <numberBetween(1, 500)>
        cashReserved: <numberBetween(1, 10)>
        cashUsed: <numberBetween(1, 10)>
        active: <boolean(95)>
        createdAt: <dateTime()>
        updatedAt: <dateTime()>
        start: <dateTimeBetween('-1 month', 'now')>
        end: <dateTimeInInterval('now' , '+ 6 months')>
        plan: '@plan<numberBetween(1, 100)>'
        # users: ['@user<current()>']
```

users is ManyToMany relation with user entity. Don't know if array of user and array of vouchers in user entity is right way ?
