### ISSUE TITLE
Strange behaviour with <password()>

### ISSUE THREAD

**Issue by Simperfit** [hautelook/AliceBundle#240]
We are using AliceBundle in order to generate some fixtures : 
Given this exemple : 
```yaml
person{4..800}:
        email: <email()>
        password: <password()>
        familyName: <firstname()>
        gender: <randomElement(['Homme', 'Femme'])>
        givenName: <lastname()>
        maidenName: <lastname()>
        aliasName: <username()>
        employer: <word()>
        unionActivity: <word()>
        observations: <word()>
        birthDate: <dateTime('now')>
        firstMembershipDate: <dateTime('now')>
        subscription: <boolean(80)>
        description: <word()>
        gender: <randomElement(['Homme', 'Femme'])>
        roles:
            - ROLE_MEMBER
```

The password part is giving us trouble : 
Changing this 
```yaml
password: <password()>
```
to this
```yaml
password: "Gerard"
```
is Working.

```bash
 /Users/hamza/projet/.../DataFixtures/ORM/fixtures/person.yml:
     - Instance py5~WE\9"H is not defined
     - Instance mask "6^"u|+WIUt*D(" did not match any existing instance, make sure the object is created after its references
     - Instance =#`@]~?2 is not defined
     - Instance Pf2s]Mo$,O6m6J7 is not defined
     - Instance mask "{2*yXW" did not match any existing instance, make sure the object is created after its references
     - Instance 3ktujOx9 is not defined
```

We are using the version : V1.3.1.

Thanks,
Simperfit.
