### ISSUE TITLE
Unable to load fixtures following the new README.md file

### ISSUE THREAD

**Issue by gitmehubb** [hautelook/AliceBundle#284]
First, the _doctrine/orm-bundle_ package provided in the "Example of installation:", as here:

```bash
composer require --dev hautelook/alice-bundle:^2.0@dev \
  theofidry/alice-data-fixtures:^1.0@dev \
  doctrine/orm-bundle \
  doctrine/orm:^2.5 \
  doctrine/data-fixtures
```
is not a valid package. Should we remove it?

But the issue is more about the loading of fixtures that is not working when following the new README.md file : it is written that we should indicate:

```yaml
# app/config/config_dev.yml

hautelook_alice:
    fixtures_path: 'Resources/fixtures/orm' # Path to which to look for fixtures relative to the bundle path.
```

Nothing happens when executing the doctrine command `php app/console hautelook:fixtures:load`

So I tried to use the previous configuration:

```yaml
# app/config/config_dev.yml

hautelook_alice:
    db_drivers:
        orm: ~          # Enable Doctrine ORM if is registered
        mongodb: ~      # Enable Doctrine ODM if is registered
        phpcr: ~        # Enable Doctrine PHPCR ODM if is registered
    locale: en_US       # Locale to used for faker; must be a valid Faker locale otherwise will fallback to en_US
    seed: 1             # A seed to make sure faker generates data consistently across runs, set to null to disable
    persist_once: false # Only persist objects once if multiple files are passed
    loading_limit: 5    # Maximum number of time the loader will try to load the files passed
```

but after launching the doctrine command, I get the following errors:
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                         
  Unrecognized options "db_drivers, locale, seed, persist_once, loading_limit" under "hautelook_alice"

Can you please review?

Best Regards,
