### ISSUE TITLE
Loading fixtures with private attributes and no setters

### ISSUE THREAD

**Issue by elegos** [hautelook/AliceBundle#301]
Hello!

I've already used Alice in the past with Liip's WebTestCase, and used to call Fixtures::load to load the fixtures in the test's database.

Now I'm trying to use Symfony's WebTestCase, and I found no easy way to do this because the `Fixtures` class doesn't exist anymore.

What I tried to do is thus the following:

1. create a new Client via `$this->client = static::createClient()`
2. got the SimpleFileLoader via `$this->loader = $this->client->getContainer()->get('nelmio_alice.file_loader.simple')`
3. then in the test I've called `$this->loader->loadFile(__DIR__.DIRECTORY_SEPARATOR.'Fixtures'.DIRECTORY_SEPARATOR.'baseUser.yml')`

The problem now is that it won't be able to hydrate private attributes with no setters, and thus it will return a sad error `Could not hydrate the property "salt" of the object "user1" (class: AppBundle\Entity\User\UserEntity)`

How can I achieve this thing? I really need to load scenarios per-test, as the database is of type sqlite and in-memory, so I can't load the fixtures with the shell command.

Thanks

EDIT: I found this page: https://github.com/nelmio/alice/blob/master/doc/advanced-guide.md#custom-accessor - but how can I register my new `PropertyHydrator`?

**Comment by theofidry** [comment]
You have:

```xml
<service id="nelmio_alice.generator.hydrator" alias="nelmio_alice.generator.hydrator.simple" />
```

So if you want to register your own, simply create it and override the service definition of `nelmio_alice.generator.hydrator` to alias your new hydrator :)

**Comment by theofidry** [comment]
Note that I understand the need of setting private properties without setters, but it's a bit more custom and having it as a global behaviour is a bit too risky IMO besides having a negligible performance impact.

**Comment by umpirsky** [comment]
Would be cool if it is disabled by default but have option to enable it.

**Comment by theofidry** [comment]
Yes it would be easier for the user, but I don't think adding some config faff for it when registering a custom service is all it takes is worth it either especially for a practice that I don't recommend.

**Comment by umpirsky** [comment]
Well, if I understood correctly, when configured like this:

```yaml
app.alice.property_access.reflection_property_accessor:
        class: Nelmio\Alice\PropertyAccess\ReflectionPropertyAccessor
        public: false
        decorates: nelmio_alice.property_accessor
        decoration_priority: -10
        arguments: ['@app.symfony.property_access.property_accessor']

app.symfony.property_access.property_accessor:
        class: Symfony\Component\PropertyAccess\PropertyAccessor
        public: false
```

it will use reflection only when `Symfony\Component\PropertyAccess\PropertyAccessor` cannot set private property (no public setter), right?

If so, why is it so bad? It should have similar performances to native if there are public setters.
