### ISSUE TITLE
manyToMany fixtures

### ISSUE THREAD

**Issue by shairyar** [hautelook/AliceBundle#302]
Hi,

I can get the oneToMany and ManyToOne to work however I am not sure how to add manyToMany fixtures. Is there any example on this?

Regards,
Baig

**Comment by theofidry** [comment]
```yaml
App\User:
  groups: '<randomNumber(0, 5)x @group*'

App\Group:
  users: '<randomNumber(0, 5)x @user*'
```

:)

**Comment by sarramegnag** [comment]
Updated answer :
```yaml
App\User:
  groups: '<numberBetween(0, 5)>x @group*'

App\Group:
  users: '<numberBetween(0, 5)>x @user*'
```
