### ISSUE TITLE
How to reference different fixtures types that start by the same name?

### ISSUE THREAD

**Issue by Kwadz** [hautelook/AliceBundle#313]
In the following example, how to make the difference between `dummy` and `dummy_configuration`?
In this case it seems _AliceBundle_ try to pass in `Product` a `DummyConfiguration` instead of a `Dummy`. 

```yaml
# app/Resources/fixtures/orm/product.yml
AppBundle\Entity\Product:
    product_{1..10}:
        name: <name()>
        dummy: '@dummy*'
```

```yaml
# app/Resources/fixtures/orm/dummy.yml
AppBundle\Entity\Dummy:
    dummy_{1..10}:
        name: <name()>
```

```yaml
# app/Resources/fixtures/orm/dummy_configuration.yml
AppBundle\Entity\DummyConfiguration:
    dummy_configuration_{1..10}:
        name: <name()>
```
