### ISSUE TITLE
Get null when trying to get an id

### ISSUE THREAD

**Issue by atallahade** [hautelook/AliceBundle#340]
Is there a way to get the id of a fixture entity?
Here is an example of what I'm trying to do:

```yml
XBundle\Entity\A
  a:
    name: 'a'
```
```yml
XBundle\Entity\B
  b:
    name: 'b'
    aId: '@a->id'
```
I get a `null` value in `aId` because the entity is not persisted yet.
I'm using doctrine as an orm.

**Comment by theofidry** [comment]
By design, if you are using auto-generated ID you cannot fully use your objects before persisting them. Either change the ID generation strategy, e.g. to use UUIDs, or load your files separately.

Alternatively you shouldn't set the ID but the relationship:

```yaml
XBundle\Entity\A
  a:
    name: 'a'
```

```yaml
XBundle\Entity\B
  b:
    name: 'b'
    a: '@a'
```
