### ISSUE TITLE
Class Name in Entity Field

### ISSUE THREAD

**Issue by pdugas** [hautelook/AliceBundle#349]
I am trying to build a YAML fixture file to load entities that have a class name in a property(field).  The use case is a schema along the same lines as the Doctrine "Loggable" extension where LogEntry objects contain `objectClass` and `objectId` fields that together refer to another object.  See the example below.

```
AppBundle\Entity\Bar:
    bar1:
        name: Bar 1
AppBundle\Entity\Foo:
    foo1:
        name: Foo 1
        objectClass: AppBundle\Entity\Bar
        objectId: '@bar1->id'
```
When I try and load this, I'm getting aLexException,  `Could not lex the value "\Entity\Bar"`. The error goes away if I comment out the `objectClass: ...` line.  

Seems to me something is trying to be "smart" about the contents of that string.  Is there a way to bypass that logic and just have it load the string? I've tried various combinations of quotes and escaping to no avail.
