### ISSUE TITLE
Entity ID is NULL

### ISSUE THREAD

**Issue by pdugas** [hautelook/AliceBundle#350]
My schema  has an entity that can be associated with a number of other types of entities.  The `objectClass` and `objectId` properties combine to reference the other entity. In my example below, I'm trying to create a `Foo` that is associated with the `Bar` entity created above it. 

```
AppBundle\Entity\Bar:
    bar1:
        name: Bar 1

AppBundle\Entity\Foo:
    foo1:
        name: Foo 1
        objectClass: <entityClass('Bar')>
        objectId: '@bar1->id'
```

When I load a fixture like this, I'm getting `null` for the `objectId` value in the database.  Actually, the field isn't allowed to be NULL so the load is failing with a constraint violation from the database. 

I suspect the issue here is that `@bar1->id` is being evaluated and substituted before the @bar1 object is actually created so the auto-generated `id` value isn't yet set. Do I need to go back to non-YAML fixtures?
