### ISSUE TITLE
Fixtures not found, what I am missing?

### ISSUE THREAD

**Issue by reypm** [hautelook/AliceBundle#355]
Hi,

I am using AliceBundle in a new project and I am following exactly the same configuration as shown [here](https://github.com/hautelook/AliceBundle#installation) meaning basically:

```
hautelook_alice:
    fixtures_path: 'Resources/fixtures/orm'
```

I have created the following files in such folder:

```
AppBundle\Entity\Post:
    post_{1..10}:
        postTitle: <text()>
        postContent: <paragraph()>
        slug: <slug()>

AppBundle\Entity\Category:
    category_1:
        categoryName: Hot
        categoryDescription: Hot topics
        slug: hot
        active: true
    category_2:
        categoryName: New
        categoryDescription: New topics
        slug: new
        active: true
```

But take a look to the following output:

```
PS C:\WINDOWS\system32> docker exec -u www-data -it reddit_webserver_1 bin/console hautelook:fixtures:load -vvv
Careful, database will be purged. Do you want to continue y/N ?y
11:23:41 INFO      [app] fixtures found
[
  "files" => []
]
[]
11:23:41 INFO      [app] fixtures loaded
[]
[]
```

What I am missing here?
