### ISSUE TITLE
Feedback from using this bundle with Symfony 4.0 (Flex)

### ISSUE THREAD

**Issue by gabiudrescu** [hautelook/AliceBundle#380]
I ran into the following problems: 
 - I had to manually declare all these bundles in config/bundles.php:
```php
    Hautelook\AliceBundle\HautelookAliceBundle::class => ['dev' => true, 'test' => true],
    Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle::class => ['dev' => true, 'test' => true],
    Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle::class => ['dev' => true, 'test' => true]
```
otherwise, flex kept complaining that FidryAliceDataFixturesBundle was not loaded - to be more specific, failed with this exception: https://github.com/hautelook/AliceBundle/blob/master/src/DependencyInjection/HautelookAliceExtension.php#L43

 - I had to change config/packages/dev/hautelook_alice.yml from:

```yml
# Read the documentation: https://github.com/hautelook/AliceBundle/blob/v1.4.1/README.md
hautelook_alice:
    db_drivers:
        orm: ~
#    locale: en_US
#    seed: 1
#    persist_once: false
#    loading_limit: 5
```

to
```yml
hautelook_alice:
    fixtures_path: 'fixtures' 
    root_dirs:
        - '%kernel.root_dir%'
        - '%kernel.project_dir%'
```
