### ISSUE TITLE
Readme faker-provider, potential bug

### ISSUE THREAD

**Issue by RomulusED69** [hautelook/AliceBundle#406]
In this file https://github.com/hautelook/AliceBundle/blob/master/doc/faker-providers.md

```
app/config/services.yml

services:
    data_fixtures.provider.foo:
        class: AppBundle\DataFixtures\Faker\Provider\FooProvider
        tags: [ { name: nelmio_alice.faker.provider } ]
```

In SF4 if bundle is not active on prod, error because tag not exist. Maybe write a warning or write in service_test.yaml
