### ISSUE TITLE
Using a name twice in a file gives a confusing error

### ISSUE THREAD

**Issue by roenschg** [hautelook/AliceBundle#408]
```yaml
AppBundle\Entity\CorrectEntity:
  my_correct_entity:
    name: "I´m the original!"
AppBundle\Entity\WrongEntity:
  my_correct_entity:
     name: "I´m a bad overwriter!
```

If you execute this you will get the error message:

> Could not determine how to assign Name to a AppBundle\Entity\CorrectEntity object

But in this case I would expect a message like:

> Could not determine how to assign Name to a AppBundle\Entity\WrongEntity object

It would be even better to give an error message that a name is used twice.

The misleading error message is coming from Populator Line 104.

The problematic code can be found in Populator line 78.

```php
$class  = $fixture->getClass();
$name   = $fixture->getName();
$object = $this->objects->get($name);
```

If I debug it I can see that in the class name is a different one than $object is type of.
