### ISSUE TITLE
RefreshDatabaseTrait works wrong

### ISSUE THREAD

**Issue by zserg84** [hautelook/AliceBundle#453]
Hi. Can you help me with RefreshDatabaseTrait
When I use RefreshDatabaseTrait, my test fails.
```php
class AccountControllerTest extends WebTestCase
{
    use RefreshDatabaseTrait;

    /**
     * @group legacy
     */
    public function testIndex(): void
    {
        $userId = '870b1d0f-e8c3-49e4-993b-25fc3c7538fc';
        $url = sprintf('%s?%s', '/api/legacy/accounts', http_build_query([
            'user_id' => $userId
        ]));
        $client = static::createClient();
        $client->request('GET', $url);
        $client->insulate();

        $data = json_decode($client->getResponse()->getContent(), true);
        $this->assertEquals(200, $client->getResponse()->getStatusCode());
        $this->assertNotEmpty($data);
        $this->assertArrayHasKey('status', $data);
        $this->assertArrayHasKey('message', $data);
        $this->assertArrayHasKey('data', $data);
        $this->assertEquals($data['status'], ResponseHelper::STATUS_SUCCESS);
        $result = $data['data'];
        $this->assertNotEmpty($result); // **Error is here**
    }
}
```
Error is 'Failed asserting that an array is not empty.'

That is my AccountController:

```php
public function index(Request $request): JsonResponse
    {
        $user = $this->getUserFromRequest($request);
        $accounts = $user->getAccounts(); // **In this line accounts are empty**
        $result = [];
        foreach ($accounts as $account) {
            $result[] = $this->serializeAccount($account);
        }

        return ResponseHelper::createSuccessResponse($result);
    }

```
Fixtures:
```yaml
App\Entity\MoneyAccount:
    account_money_1:
        idString: '3176423f-0789-4237-944e-315d472b81aa'
        user: '@user_1'
        balance: 0
        currency_code: GBP
        status: available

App\Entity\User:
    user_1:
        idString: '870b1d0f-e8c3-49e4-993b-25fc3c7538fc'
        password: pass
        roles: ["ROLE_USER"]
```

And without RefreshDatabaseTrait everything is ok. Test passes correctly.
