### ISSUE TITLE
Alice fixtures - Notice: Array to string conversion

### ISSUE THREAD

**Issue by tudorluchy** [hautelook/AliceBundle#455]
I use alice bundle and theofidry to make fixture to my mongodb.

I just want to use an array in my fixtures, that's all.

I want to use an array for my subcategories of a category but I always have the same problem.

I load my files with : 
$loader = $container->get('fidry_alice_data_fixtures.loader.doctrine_mongodb');

joboffer_category.yml

```
App\Document\JobOfferCategory:
joboffer_category_1:
    name: 'Commerce / Communication'
    code: 'COM'
    subCategories: [a, b ,c]
```

JobOfferCategory.php

```php
/**
 * @var array $subCategories
 * @ODM\Field(name="collection")
 * @Expose
 */
protected $subCategories;

/**
 * @return array
 */
public function getSubCategories(): array
{
    return $this->subCategories;
}

/**
 * @param array $subCategories
 * @return JobOfferCategory
 */
public function setSubCategories(array $subCategories)
{
    $this->subCategories = $subCategories;
    return $this;
}
```

The problem :

```bash
$ docker-compose exec app php bin/console doctrine:mongodb:fixtures:load --no-interaction
  > purging database
  > loading [10] App\DataFixtures\MongoDB\AliceFixtures

In StringType.php line 31:

Notice: Array to string conversion

```
