### ISSUE TITLE
Is it possible to call methods with Symfony services intances?

### ISSUE THREAD

**Issue by Kocal** [hautelook/AliceBundle#456]
Hi, I'm having an issue when writing fixtures that should call a method that takes a service instance.

I'm writing fixtures for configuring some payment gateways (for [Payum](https://github.com/Payum/Payum)). 
It's works fine unless I try to encrypt them, because I don't know how to do that.

This is what I have actually:

```yaml
App\Entity\Payment\GatewayConfig:
  first_gateway_config:
    gatewayName: 'gateway_1'
    factoryName: 'system_pay'
    config:
      sandbox: true
      field_1: "XXX"
      field_2: "YYY"
```

Fields `gatewayName` and `factoryName` will be stored in plain text, but `config` should be encrypted.

My entity `App\Entity\Payment\GatewayConfig` extends from [`Payum\Core\Model\GatewayConfig`](https://github.com/Payum/Payum/blob/master/src/Payum/Core/Model/GatewayConfig.php), so I should call `$gatewayConfig->encrypt($cypher)` method, where `$cypher` is a `Payum\Core\Security\CypherInterface`.

So I thought about adding a new call like this, but of course it does not work:

```yaml
App\Entity\Payment\GatewayConfig:
  first_gateway_config:
    gatewayName: 'gateway_1'
    factoryName: 'system_pay'
    config:
      sandbox: true
      field_1: "XXX"
      field_2: "YYY"
    __calls:
      - encrypt: [<(Payum\Core\Security\CypherInterface::class)>]
```

Does someone here have already encountered the same issue? Is there a way to do this?

Thanks!

**Comment by theofidry** [comment]
The easiest way I think would be to register a custom faker provider

**Comment by Kocal** [comment]
I already thought about it, but I don't know how to use it.

Faker providers only work on entity's fields and not entity itself, right? :thinking:

**Comment by theofidry** [comment]
You can the entity itself with `@self` IIRC`

**Comment by Kocal** [comment]
Oh, didn't know about this.

So I suppose I will have to create a custom Faker Provider (e.g. `EncryptGatewayConfig`), register it, and call `<encryptGatewayConfig(@self)>`, but how/where should I call it? I can't put it on a field right?

**Comment by theofidry** [comment]
Ah I see what you mean. Maybe you can try:

```yaml
App\Entity\Payment\GatewayConfig:
  first_gateway_config:
    gatewayName: 'gateway_1'
    factoryName: 'system_pay'
    config:
      sandbox: true
      field_1: "XXX"
      field_2: "YYY"
    __calls:
      - '@my-encrypt-service::encrypt': ['@self']
```

[It works for factories](https://github.com/hautelook/AliceBundle/blob/master/doc/advanced-usage.md#use-service-factories) but I don't know about regular calls.

Alternatively you can register a pre-processor to do the necessary calls on your object
