### ISSUE TITLE
I can't get the mongodb id from object

### ISSUE THREAD

**Issue by tudorluchy** [hautelook/AliceBundle#457]
Hello,

My problem is **I can't get the id of an object created with alice fixture**.
It's very simple : 

DegreeOfEducation.php
```php
class DegreeOfEducation
{
    /**
     * @var \MongoId $id
     * @ODM\Id()
     * @Expose
     */
    private $id;

    /**
     * @var string $name
     * @ODM\Field(type="string")
     * @Assert\NotBlank(message="Le nom n'est pas valide.")
     * @Expose
     */
    private $name;
```

degreeofeducation.yml

```yml
App\Document\DegreeOfEducation:
    degreeofeducation_0:
        name: "BAC"
        description: <fr_FR:text()>
```

In the database I have the degreeofeducation created with _id : ObjectId("5c58781ffc61ca02b74251c2")
All right.

I have another class **JobOfferDegreeOfEducationEmbedded** where I want to embed the **id** and the **name**.

JobOfferDegreeOfEducationEmbedded.php
```php
class JobOfferDegreeOfEducationEmbedded
{
    /**
     * @var \MongoId $id
     * @ODM\Field(type="string")
     * @Expose
     */
    private $id;
```
The problem is when I call "**@degreeofeducation_0->id**" in my fixture I get no ID. In the database I have only the name. Why ? I think because the ID is not persisted yet to database but how can I resolve this problem ?

**joboffer.yml**
```yml
App\Document\JobOfferDegreeOfEducationEmbedded:
    joboffer_degreeofeducation_emb_1:
        id: '@degreeofeducation_0->id'
        name: '@degreeofeducation_0->name'
```

Thank you a lot !
