### ISSUE TITLE
Load fixtures in a specific order

### ISSUE THREAD

**Issue by oenie** [hautelook/AliceBundle#469]
I am trying to work with Doctrine and the Alice bundle but have run into a circular dependency problem of some sort.

It's kind of hard to see where this is happening, I have tried the reordering as per the 
[Advanced usage](https://github.com/hautelook/AliceBundle/blob/master/doc/advanced-usage.md#persisting-the-classes-in-a-specific-order) but that does not seem to help.

It gives me a different order than when the persisting actually happens. I suspect thisis due the 'automatic fixing of circular references' ? If so, it seems to me that something is wrong in some situations. 

The fixtures that seem to be giving me the headache are the ones with a __construct method that needs the arguments for FK constraints like below:

```yaml
AppBundle\Entity\SignLocation:
    signLocation (template):
        active: true
        tenant: '@tenant1'
        location: <geoPointBelgium()>

    signLocation1 (extends signLocation):
        __construct: ['@sign1', '@parkingBanIntake1']
```

In this case the `@Sign1` reference is not yet loaded when the `SignLocation` entity is being persisted, resulting a `NULL` value constraint violation (because `sign_id` in its table has a non null constraint) 

Is there a way (as is mentioned in the Doctrine fixtures manual) to signal that a certain object relies on another one ? Excuse me if this issue is a bit vague, I will try to provide more information if needed :)
