### ISSUE TITLE
Property Accessing

### ISSUE THREAD

**Issue by MylesKingsnorth01** [hautelook/AliceBundle#474]
How can I access properties? I have the following fixture:

```yaml
App\Entity\Foo:
    foo_{1..100}:
        name (unique): <company()>
        example: <sentence(2)>
```

Now on my Bar entity, I'd like to access the example property to get the value

```yaml
App\Entity\Bar:
    bar_{@foo_*}:
        name: <name()>
        example_2: <current()>.example
```

This just returns me the `__toString` result of my Foo entity and appends '.example' onto the end.

I used the following documentation to kind of determine how properties should be accessed, [here](https://github.com/nelmio/alice/blob/master/doc/advanced-guide.md#property-reference).
