### ISSUE TITLE
ManyToMany and cascading

### ISSUE THREAD

**Issue by hhoechtl** [hautelook/AliceBundle#478]
Having these 2 fixtures:
```yaml
App\Entity\Location:
  location_AF:
    name: Afghanistan
    flag: '/static/flag/af.png'
  location_AX:
    name: 'Åland Islands'
    flag: '/static/flag/ax.png'
  location_AL:
    name: Albania
    flag: '/static/flag/al.png'
App\Entity\Client:
    client_{1..300}:
        name: <company()>
        location: '@location_*'
        areaOfServices (unique): '<numberBetween(1, 10)>x @location_*'
```

With the model:
```php
class Client
{
    /**
     * @var Collection<Location>
     * @ORM\ManyToMany(targetEntity="Location")
     */
    private $areaOfServices;
```

The location has no relation to client.

It either generates duplicate Location entities if I add `, cascade={"persist"}` or throws an exception:
```
 * A new entity was found through the relationship 'App\Entity\Client#areaOfServices' that was not configured to cascade persist operations for entity: App\Entity\Locati  
  on@000000003500464b00000000092ef5b6. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this associa  
  tion in the mapping for example @ManyToOne(..,cascade={"persist"}). 
```

The order of the models in the `LoaderInterface` would be correct. First locations, then clients. But I think the problem is that the generated locations which are assigned to the clients are not references to the location fixtures, which causes the duplicates or the error.

So there must be a way to first persist the location fixtures and then use them as reference fot the client assignment `areaOfServices`
