### ISSUE TITLE
Duplicated records in database when loading fixtures

### ISSUE THREAD

**Issue by Brewal** [hautelook/AliceBundle#479]
I have a Language entity with this fixtures yaml file : 

```yaml
App\Entity\Taxonomy\Language:
    language_fr:
        name: 'Français'
        active: true
        code (unique): 'fr'
        default: true
    language_en:
        name: 'English'
        active: true
        code (unique): 'en'
        default: false
```

Then I have 3 other entities : 

**Spot**
```yaml
App\Entity\Spot:
    spot_{1..40}:
        name: '<word()>'
        defaultLanguage: '@language_*'
        address (unique): '@address_*'
        description: <text()>
        magicSeaweedId: <word()>
```

**Address**
```yaml
App\Entity\Address:
    address_{1..150}:
        address1: <streetAddress()>
        address2: '50%? <streetAddress()>'
        postalCode: <postcode()>
        city: <city()>
        latitude: <latitude()>
        longitude: <longitude()>
        state: <state()>
        department: <state()>
        timezone: <timezone()>
        country: '@country_*'
```

**Country**
```yaml
App\Entity\Taxonomy\Country:
    country_{1..20}:
        name (unique): '<country()>'
        defaultLanguage: '@language_*'
        active: '<boolean()>'
        hasStates: '<boolean()>'
        isoCode: '<word()>'
        phoneCode: '<word()>'
```

As you can see, both Country and Spot entities are related to the Language entity.
I'm facing a strange issue when I load the fixtures of my project : I can see that the language table contains many duplicated records of en and fr languages instead of only two.

You can see the entities and reproduce the bug with this project : 

https://github.com/Brewal/alice-duplicated-fixtures

I might be doing something wrong here but I'm really struggling with this issue ! Some help would be appreciated :)
