### ISSUE TITLE
Allow literal strings (without processing)

### ISSUE THREAD

**Issue by tacman** [hautelook/AliceBundle#492]
I'd like to be able to put a literal value into a field.  It's been discussed before, using <identity()> and faker functions, but it still is very hard to put things like URLs and regexes into fixtures.

How about back-ticks?  E.g.

```yaml
config:
    url:  `http://something.com?abc&123`
    headline: `Budget approved for $200 Euros (FRANCE)`
```
Yes, I know AliceBundle is great for generating fake fixtures, but I have also been using it for isolating data from a large database to create a small test case.  So I dump my data to a YAML file, which I can then load when I just want to test that problem dataset.  This bundle handles related entities so nicely that I'd love to be able to use it.

Thanks.
