### ISSUE TITLE
Issue on ValueObject with private constructor / __factory

### ISSUE THREAD

**Issue by flim** [hautelook/AliceBundle#507]
My value object has a private constructor with a static method `create` that instanciate and return my new object.

Im using the `__factory` key in the fixtures.yml but when im tried to load, I got the message 
```yaml
App\Entity\ValueObject\MyVo:
  vo:
    __factory: { 'App\Entity\ValueObject\MyVo::create': ['arg1', 'arg2', 'arg3'] }
```
```
Invalid service "App\Entity\ValueObject\MyVo": its constructor must be public. 
```

Why does it try to use the constructor ?
