### ISSUE TITLE
LogicException: No ID found for the entity

### ISSUE THREAD

**Issue by develth** [hautelook/AliceBundle#516]
Hi,

until my today performed composer update the fixtures worked really nice -thanks for that!

Now, i get the following:

```
No ID found for the entity "App\Entity\PaymentMethod". If this entity has a  
  n auto ID generator, this may be due to having it disabled because one inst  
  ance of the entity had an ID assigned. Either remove this assigned ID to al  
  low the auto ID generator to operate or generate and ID for all the "App\En  
  tity\PaymentMethod" entities. 
```
I digged into debugging and recognized, that almost all PaymentMethods have a ID - until the last one from ```payment_method{1..50}```:

```
App\Entity\PaymentMethod:
  payment_method{1..50}:
    name: <word()>
    text: <realText(200)>
  payment_method_to_delete:
    name: 'hey_delete_me'
    text: <realText(200)>
  payment_method_to_update:
    name: 'hey_update_me'
    text: <realText(200)>
  payment_method_detail_tenant:
    name: 'hey_detail'
    text: <realText(200)>
```

Any idea how to fix it?

Thanks!
