### ISSUE TITLE
Unable to hydrate a foreign key in relation

### ISSUE THREAD

**Issue by drupol** [hautelook/AliceBundle#524]
Hello,

I have this database schema ([link to db diagram](https://dbdiagram.io/d/5fc5f3413a78976d7b7e068e)).
Each tables has composite (compound) primary keys with foreign keys.

I would like to create fixtures for the Table C.

According to the documentation, I guess that one solution would be:

```yaml
App\Entity\TableC:
  TableC{1..100}:
    cpk1: <numberBetween()>
    bfk1: '<current()>->tableB->bfk1'
    bfk2: '<current()>->tableB->bfk2'
    afk1: '<current()>->tableB->afk1'
    afk2: '<current()>->tableB->afk2'
    tableB: '@TableB<current()>'
```

But that is not working.

In order to get it working, I have:

1.  Add a relation to Table A in Table C:

```php
    /**
     * @ORM\ManyToOne(targetEntity=TableA::class)
     * @ORM\JoinColumns(
     *     @ORM\JoinColumn(name="AFK1", referencedColumnName="APK1"),
     *     @ORM\JoinColumn(name="AFK2", referencedColumnName="APK2"),
     * )
     */
    public $tableA;
```

2. Update the fixture:

```yaml
App\Entity\TableC:
  TableC{1..100}:
    cpk1: <numberBetween()>
    bfk1: '<current()>->tableB->bfk1'
    bfk2: '<current()>->tableB->bfk2'
    afk1: '<current()>->tableB->afk1'
    afk2: '<current()>->tableB->afk2'
    tableB: '@TableB<current()>'
    tableA: '@TableA<current()>'
```

To be honest, I don't like this solution, this is why I found it ugly ([see commit](https://github.com/drupol/composite/pull/5)).

I succeeded to do it successfully for Table A and B ([see PR](https://github.com/drupol/composite/pull/4)) but not for Table B and C. I'm trying to find a better solution, but I'm running out of ideas.
