### ISSUE TITLE
Load fixtures, error with mt_rand()

### ISSUE THREAD

**Issue by julienmiclo** [hautelook/AliceBundle#536]
Hello,
i am starting new project and i want try this bundle but after reading documentation and create my yaml files, when i do hautelook:fixtures:load, i have this error :

**In SimpleObjectGenerator.php line 111: An error occurred while generating the fixture "user1" (App\Entity\User): mt_rand(): Argument _#2 ($max) must be of type int, string given**

**In Base.php line 140: mt_rand(): Argument _#2 ($max) must be of type int, string given**

```yml
@/fixtures/fixtures.yml
  App\Entity\User:
    user{1..10}:
        username: <userName()>
        email: <safeEmail()>
        password: <password('password')>
```

Can you tell me what's wrong with my configuration ?

Thank you

---

symfony: 5.2.5
"doctrine/doctrine-fixtures-bundle": "^3.4"
"hautelook/alice-bundle": "^2.9"
