### ISSUE TITLE
Could not find a variable "$argon2id"

### ISSUE THREAD

**Issue by lobodol** [hautelook/AliceBundle#539]
Hello there,

I'm working a Symfony 5.2.6 project, and I'd like to load fixtures for my `User` entity.

The `User` class implements [`Symfony\Component\Security\Core\User\UserInterface`](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Security/Core/User/UserInterface.php) (thus, it has a `password` field).

The security package is configured to chose automatically the hashing algorithm:

```yaml
# config/packages/security.yaml
security:
    encoders:
        App\Entity\User:
            algorithm: auto
```

Here is my fixture file:

```yaml
# fixtures/users.yaml
App\Entity\User:
    user0:
        username: Bob
        password: "$argon2id$v=19$m=65536,t=4,p=1$f9es7aTra9ei+d0ftpN1fw$Mn894CU84NQs4fXCxlXNKwbQ/iWMDCzF++2GMEz8Qys"
```

I used the following command to generate the value of `password`:

```bash
bin/console security:encode-password
```

Finally, when I run command `bin/console hautelook:fixtures:load` I've got the following errors:

```
In SimpleObjectGenerator.php line 111:
                                                                                                                                    
  An error occurred while generating the fixture "user0" (App\Entity\User): Could not resolve value during the generation process.  
                                                                                                                                    

In UnresolvableValueDuringGenerationExceptionFactory.php line 25:
                                                          
  Could not resolve value during the generation process.  
                                                          

In UnresolvableValueExceptionFactory.php line 77:
                                          
  Could not find a variable "$argon2id".  
```

It seems like `$argon2id` is interpreted as a variable. I tried to escape it by adding backslashes or changing double quotes by simple ones but the errors persist.

How can I handle this? I saw nothing in the documentation about variable interpretation.

Thanks for reading,

Regards,
